library(shiny)
library(shinyBS)
require(rCharts)

shinyUI(fluidPage(
  titlePanel("Plate Reader Data Analysis"),
  sidebarLayout(
    sidebarPanel(
      bsTooltip(id="datafile",title="Currently supporting Excel files generated by Tecan readers only. Uploading a single file will treat it as a series of measurements in time. Uploading multiple files will assume each file represents a single measurement. In this case the number of plates must be specified and files will be read in an interleaved manner, assuming the files cycle through the plates",placement="right", trigger="hover"),
      fileInput("datafile","Excel reader data file/s:",multiple=TRUE),
      conditionalPanel(
        condition="output.MultiFile",
        textInput("platesnum","Number of plates",value=""),
        textInput("platenum","Plate to analyze",value="1")
      ),
      conditionalPanel(
        condition="output.fileUploaded",
        bsTooltip(id="descfile",title="Upload optional plate description file (Excel) to label wells",placement="right", trigger="hover"),
        fileInput("descfile","Plate description file"),
        selectInput(
          inputId = "wellsToAnalyse",
          label = "Wells to analyse",
          choices = c("Whole plate","Row","Column","Wells"),
          selected = 1),
        conditionalPanel(
          condition='input.wellsToAnalyse == "Wells"',
          textInput("wells","Wells to analyse",value="A1")
        ),
        conditionalPanel(
          condition='input.wellsToAnalyse == "Row"',
          htmlOutput("rowSelect")
        ),
        conditionalPanel(
          condition='input.wellsToAnalyse == "Column"',
          htmlOutput("columnSelect")
        ),
        selectInput(
          inputId = "analysisType",
          label = "Data to display",
          choices = c("Plate overview","Growth rate analysis","Plotly test"),
          selected = 1
          ),
        conditionalPanel(
          condition='input.analysisType == "Growth rate analysis" || input.analysisType == "Plotly test"',
          htmlOutput("labelSelect"),
          selectInput(
            inputId = "backgroundMethod",
            label = "Background subtraction method",
            choices = c("Average of first measurements of well",
                        "Time average of blank wells",
                        "Point-wise average of blank wells",
                        "Manual value"),
            selected = 1
            ),
          conditionalPanel(
            condition='input.backgroundMethod == "Manual value"',
            textInput("manualBackground","Background value to use",value="0.0")            
            ),
          conditionalPanel(
            condition='input.backgroundMethod == "Time average of blank wells" || input.backgroundMethod == "Point-wise average of blank wells"',
            textInput("blankWells","Blank wells to use",value="A1")            
            ),
          conditionalPanel(
            condition='input.backgroundMethod == "Average of first measurements of well"',
            textInput("perWellMesNum","Number of measurements to use",value="1")            
            ),
          checkboxGroupInput("grPlots","Plots to display",c("raw",
                                                            "background subtracted",
                                                            "background subtracted log",
                                                            "growth rate vs. time",
                                                            "doubling time vs. time",
                                                            "growth rate vs. value",
                                                            "doubling time vs. value"),
                             selected=c("background subtracted log",
                                        "doubling time vs. time",
                                        "doubling time vs. value")),
          textInput("windowSize","Growth rate window size",value="5"),
          checkboxInput("errorBars","Show error bars"),
          textInput("maxdtime","Maximum doubling time in minutes",value="300"),
          textInput("rsquare","R-square threshold",value="0.9")
          )
        )
      ),
    mainPanel(
      conditionalPanel(
        condition="! output.fileUploaded",
        includeHTML("welcome.html")
        ),
      conditionalPanel(
        condition='output.fileUploaded && (input.analysisType == "Growth rate analysis")', 
        h3("Growth rate analysis")
        ),
      conditionalPanel(
        condition='output.fileUploaded && (input.analysisType == "Plate overview")', 
        h3("Plate overview")
        ),
      conditionalPanel(
        condition='(input.analysisType == "Plate overview") || (input.analysisType == "Growth rate analysis")', 
        htmlOutput("plots")
        ),
      conditionalPanel(
        condition='input.analysisType == "Plotly test"',
        showOutput("myChart","highcharts")
        )
      )    
    )
  ))
